### ISSUE TITLE
Facing issues with setting up the project locally 

### ISSUE THREAD

**Issue by pSN0W** [Samagra-Development/PDF-Package#36]
I forked and cloned the project and the upon running the 
> sudo docker-compse up -d 
I am facing this error. I am not familiar with docker so please help me sort this out.
`
sn0w@pratyaksh:~/Desktop/India/Doc-Generator$ sudo docker-compose up -d
WARNING: The DB_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The DB_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The DB_NAME variable is not set. Defaulting to a blank string.
WARNING: The HASURA_VERSION variable is not set. Defaulting to a blank string.
WARNING: The HASURA_ADMIN_PASS variable is not set. Defaulting to a blank string.
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1107, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1088, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 542, in up
    svc.ensure_image_exists(do_build=do_build, silent=silent, cli=cli)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 354, in ensure_image_exists
    self.image()
  File "/usr/lib/python3/dist-packages/compose/service.py", line 380, in image
    return self.client.inspect_image(self.image_name)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 16, in wrapped
    raise errors.NullResource(
docker.errors.NullResource: Resource ID was not provided

`

**Comment by radhay-samagra** [comment]
Hey @pSN0W,
It seems you are not importing the .env file properly. The docker-compose file is not able to read the required environment variables.

**Comment by pSN0W** [comment]
Hey @radhay-samagra thank you for your reply. The above problem is solved but now I have a new issue. My server at localhost:8000 doesn't seem to start after doing docker up.
The commands I have ran till now
Fork the repo
> git clone https://github.com/pSN0W/Doc-Generator.git

> cd Doc-Generator

> cp .env.sample .env

> sudo docker-compse up -d

> sudo docker exec -it doc-generator_web_1 bash

> python3 manage.py runserver

I get error here. The error message is as shown below
`2022-06-07 19:46:40,978 django.utils.autoreload run_with_reloader Watching for file changes with StatReloader
Performing system checks...

Exception ignored in: 'FieldInitializationWarning'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: the static field 'transparent' of type 'aspose.pydrawing.Brushes' is not initialized
Exception ignored in: 'FieldInitializationWarning'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: the static field 'alice_blue' of type 'aspose.pydrawing.Brushes' is not initialized
Exception ignored in: 'FieldInitializationWarning'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: the static field 'antique_white' of type 'aspose.pydrawing.Brushes' is not initialized
System check identified no issues (0 silenced).
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "postgres"


The above exception was the direct cause of the following exception:

`Traceback(most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check_migrations()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 486, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/loader.py", line 220, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/recorder.py", line 55, in has_table
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "postgres"
`

**Comment by dikshita-jain-13** [comment]
Hey,
I tried running it on gitpod.
But I'm getting this error -
failed to solve: executor failed running [/bin/sh -c apt-get -qq -y update &&     DEBIAN_FRONTEND=noninteractive apt-get -qq -y install     python3-dev python3-pip postgresql postgresql-contrib libffi-dev libpq-dev gcc musl-dev wkhtmltopdf sudo]: exit code: 100

**Comment by pSN0W** [comment]
> Hey, I tried running it on gitpod. But I'm getting this error - failed to solve: executor failed running [/bin/sh -c apt-get -qq -y update && DEBIAN_FRONTEND=noninteractive apt-get -qq -y install python3-dev python3-pip postgresql postgresql-contrib libffi-dev libpq-dev gcc musl-dev wkhtmltopdf sudo]: exit code: 100

Yeah I am also facing similar issue on gitpod

**Comment by RyanWalker277** [comment]
Hey @pSN0W , Looks like you have not updated the password for your postgres user in the .env file , make sure you use the right password.The error clearly shows that password authentication for the postgres user has failed , so , make sure you have set up correct credentials for your postgres user.

**Comment by Bug-Coding** [comment]
@pSN0W try this command , docker run --name  (containername) -it -p 3000:3000 -d (name)
